export const ROUTE_CONSTANTS = {
  HOME: '/',
  INBOX: '/inbox',
  TODAY: '/today',
  REVIEW: '/review',
  INSIGHTS: '/insights',
  SETTINGS: '/settings',

};

export const API_ENDPOINTS = {
  BASE_URL: process.env.REACT_APP_API_ENDPOINT || '',
  HEALTH: '/health',
  TASKS: '/api/tasks',
  TASKS_BATCH: '/api/tasks/batch',
  PLANS_GENERATE: '/api/plans/generate',
  PLANS_TODAY: '/api/plans/today',
  FEEDBACK: '/api/feedback',
  HISTORY: '/api/history',
  STATS: '/api/stats',
  WEEKLY_SUMMARY: '/api/weekly-summary',
  REVIEW_INSIGHTS: '/api/review-insights',
  SETTINGS_LLM: '/api/settings/llm',
  SETTINGS_LLM_TEST: '/api/settings/llm/test',
  SESSION: '/api/session',
  SESSION_LOGIN: '/api/session/login',
  SESSION_LOGOUT: '/api/session/logout',
  ONBOARDING: '/api/onboarding',
  ONBOARDING_COMPLETE: '/api/onboarding/complete',
  MOOD: '/api/mood',
  MOOD_TODAY: '/api/mood/today',
  MOOD_HISTORY: '/api/mood/history',
  FOCUS_SESSIONS: '/api/focus/sessions',
  FOCUS_STATS: '/api/focus/stats',
  FOCUS_HISTORY: '/api/focus/history',
  SONGS_RECOMMEND: '/api/songs/recommend',
  FORTUNE_DAILY: '/api/fortune/daily',
  FORTUNE_TODAY: '/api/fortune/today',
  ASSISTANT_STATE: '/api/assistant/state',
  ASSISTANT_CHAT: '/api/assistant/chat',
};
